apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rk4ld7l9x-dotnet-basic 
  janus-idp.io/tekton: rk4ld7l9x-dotnet-basic
  backstage.io/kubernetes-id: rk4ld7l9x-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rk4ld7l9x-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml